# Description: A basic GNU/linux filesystem
# URL: http://www.buildgear.org

name=fs
version=1.0
release=1
options=(nostrip)
source=(modules-load.d.rpi3.conf)
depends=(core
         linux
         wiringpi
         lighttpd
         php
         i2c-tools
         avahi)

build() {
   # Copy fully populated sysroot
   cp -a $SYSROOT/* $PKG

   # Set host name
   echo "rpi3" > $PKG/etc/hostname

   # Set login issue
   echo -e "Raspberry Pi 3 Mini Distribution $version\n" > $PKG/etc/issue

   # Configure network interface
   sed -i "s/NETWORK_INTERFACE_NAME/eth0/g" $PKG/etc/systemd/network/dhcp.network

   # Allow SSH root login
   sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" $PKG/etc/ssh/sshd_config

   # Enable SSH server
   ln -s /etc/systemd/system/sshd.socket \
         $PKG/etc/systemd/system/sockets.target.wants/sshd.socket
   ln -s /etc/systemd/system/sshdgenkeys.service \
         $PKG/etc/systemd/system/multi-user.target.wants/sshdgenkeys.service

   # Enable Lighttpd web server
   ln -s /etc/systemd/system/lighttpd.service \
         $PKG/etc/systemd/system/multi-user.target.wants/lighttpd.service

   # Enable avahi service
   ln -s /etc/systemd/system/avahi-daemon.service \
         $PKG/etc/systemd/system/dbus-org.freedesktop.Avahi.service
   ln -s /etc/systemd/system/avahi-daemon.service \
         $PKG/etc/systemd/system/multi-user.target.wants/avahi-daemon.service
   ln -s /etc/systemd/system/avahi-daemon.socket \
         $PKG/etc/systemd/system/sockets.target.wants/avahi-daemon.socket

   # Help load kernel modules that don't load automatically
   install -D -m 644 $SRC/modules-load.d.rpi3.conf $PKG/etc/modules-load.d/rpi3.conf

   # Cleanup
   cd $PKG/usr/include; rm -rf !(python|python?.?)
   find $PKG/usr/lib -name '*.a'    -delete -o \
                     -name '*.la'   -delete

   # Create tarball
   tar -C $PKG -Ipixz -cpf $OUTPUT/fs.tar.xz .
}

check() {
   check_tool pixz "Available in Ubuntu package pixz"
}
